### ISSUE TITLE
Constants are required when using FromUri

### ISSUE THREAD

**Issue by spencerkittleson** [LambdaSharp/LambdaSharpTool#130]
When using [FromUri] in a `ALambdaApiGatewayFunction` constants are required parameter by API Gateway. In this example, `TEST` is required. It shouldn't be.

Module.yml
```yml
 - Function: APILambda
    Description: Lambda function to handle API request/responses
    Memory: 512
    Timeout: 30
    Sources:
      - Api: GET:/
        Invoke: GetItems
```

```c# 
MyResponse GetItems([FromUri] RequestModel) { ... }

public class RequestModel {

        //--- Constants ---
        public const string TEST = "foo";

        //--- Properties ---
        [JsonProperty("filter")]
        public string Filter {
            get; set;
        }
}
```
