### ISSUE TITLE
DeploymentPrefix without the Dash

### ISSUE THREAD

**Issue by spencerkittleson** [LambdaSharp/LambdaSharpTool#132]
`DeploymentPrefix` and `DeploymentPrefixLowercase` without dashes at the end.  Maybe `Deployment` and `DeploymentLowercase`

Use case Module.yml
```yml
  - Resource: ServiceParameter
    Description: example service parameter
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub "/${DeploymentLowercase}/service/property"
      Type: String
      Value: "foo"
```

Workaround has been the following:
```yml
 - Variable: Tier
    Value: !Select [ "0", !Split [ '-' , !Sub '${DeploymentPrefixLowercase}' ] ]
```
