### ISSUE TITLE
Support for specifying PermissionsBoundary on LambdaSharp generated roles

### ISSUE THREAD

**Issue by yurigorokhov** [LambdaSharp/LambdaSharpTool#145]
Some enterprise AWS environments require role creations to specify the `PermissionsBoundary` property: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-iam-role.html#cfn-iam-role-permissionsboundary

This property should support some CFN parameters such as `AccountId`, example:
```
PermissionsBoundary: !Sub 'arn:aws:iam::${AWS::AccountId}:policy/permissions-boundaries'
```

Currently this is blocker for using LambdaSharpTool on those environments.

Happy to help with a PR if an approach is agreed upon.

**Comment by bjorg** [comment]
So this issue changed from configuring the API Gateway role for the account to setting permission boundaries on the generated IAM role for the functions? How are they related?

For the previous issue, it would be easy to add a `--skip-apigateway-check` option to `init`. Assuming, it's still needed.

The second issue, I would add a [module pragma](https://lambdasharp.net/syntax/Module-Pragmas.html) to set additional properties on a global resource.

Something like:
```
Pragmas:
  - Overrides:
      Module::Role.PermissionsBoundary: !Sub 'arn:aws:iam::${AWS::AccountId}:policy/permissions-boundaries'
```
```

**Comment by bjorg** [comment]
And by _add_, I mean add it to the tool. The logic currently doesn't allow for easily adding generic properties, so each must be supported individually.

**Comment by yurigorokhov** [comment]
The original APIGateway issue was a Symptom of the missing permission boundary for me. That is the bigger issue that needs addressing (as all roles fail to create, not just the API Gateway one).

I’d be happy to take a crack at your proposed solution (pragma) it if you give me the go ahead.

**Comment by yurigorokhov** [comment]
@bjorg they are related in that in this environment ALL roles need to have the permission boundary. (APIGateway role generated in the init, the lambda function role that is deployed later, as well as any other roles generated by the tool.

Does your propose solution still work? Or does it only apply to the function role?

**Comment by bjorg** [comment]
LambdaSharp certainly generates the `Module::Role` and that is a critical component.

For the API Gateway, LambdaSharp performs a check to see if a role already exist. If none exists, it creates a vanilla role, which would also cause your issue. After the role is created, it attaches two managed policies to allow the API Gateway to write to CloudWatch logs and X-Ray if it can't find them already attached.
https://github.com/LambdaSharp/LambdaSharpTool/blob/master/src/LambdaSharp.Tool/Cli/CliInitCommand.cs#L621

Are you sure that adding `PermissionsBoundary: !Sub 'arn:aws:iam::${AWS::AccountId}:policy/permissions-boundaries'` to the API Gateway role would be sufficient to solve your issue? Since LambdaSharp only creates the API Gateway role if none exists, can you create it yourself ahead of time to confirm?

**Comment by yurigorokhov** [comment]
Confirmed that the following role solves my issue:

```
AWSTemplateFormatVersion: 2010-09-09
Description: TestRole


Resources:
  TestRole:
    Type: AWS::IAM::Role
    Properties:
      PermissionsBoundary: !Sub 'arn:aws:iam::${AWS::AccountId}:policy/[REDACTED]'
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonAPIGatewayPushToCloudWatchLogs
        - arn:aws:iam::aws:policy/AWSXrayWriteOnlyAccess
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          -
            Sid: "ApiGatewayPrincipal"
            Effect: "Allow"
            Principal:
              Service:
                - apigateway.amazonaws.com
            Action: "sts:AssumeRole"

```
