### ISSUE TITLE
VpcFunctionSample parameters not working as expected

### ISSUE THREAD

**Issue by yurigorokhov** [LambdaSharp/LambdaSharpTool#147]
https://github.com/LambdaSharp/LambdaSharpTool/blob/d6ba89d8c606590f21fcee0dc5015859be4da144/Samples/VpcFunctionSample/Module.yml#L32

Should the `VpcConfig` be using `!Split` or am I doing something wrong?

This works:
```
VpcConfig:
  SecurityGroupIds: !Split [ ",", !Ref SecurityGroupIds ]
  SubnetIds: !Split [ ",", !Ref SubnetIds ]
```

Parameters file:
```
SecurityGroupIds:
  - sg-009a24967393f87c0
SubnetIds: 
  - subnet-0abde2ab42ca91230
```

Without `!Split` I get the following error:

```
ERROR: UPDATE_FAILED MyFunction [AWS::Lambda::Function]: Value of property SecurityGroupIds must be of type List of String 
```

**Comment by yurigorokhov** [comment]
https://github.com/LambdaSharp/LambdaSharpTool/pull/148

**Comment by bjorg** [comment]
That is unexpected. I thought `CommaDelimitedString` would be an array automatically, otherwise it acts the same as `String`. So what would be the point?

**Comment by bjorg** [comment]
Could you try passing in two comma-delimited values? For example:
```yaml
SecurityGroupIds:
  - sg-009a24967393f87c0,sg-009a24967393f87c1
SubnetIds: 
  - subnet-0abde2ab42ca91230,subnet-0abde2ab42ca91231
```
