### ISSUE TITLE
`AWS::ApiGateway::DomainName` type throws error `Property DomainName cannot be empty`

### ISSUE THREAD

**Issue by pattyr** [LambdaSharp/LambdaSharpTool#22]
`DomainName` is stripped from the type `AWS::ApiGateway::DomainName` when CloudFormation template is generated.

-------

This setting in Deploy.yml:
```
Variables:
    EndpointDomainName: "bobsharptest.mindtouch.io"

.
.
.

  - Name: ApiGatewayDomainName
    Description: Domain name to be used in the api endpoint
    Resource:
      Type: AWS::ApiGateway::DomainName
      Properties:
        DomainName: "{{EndpointDomainName}}"
        CertificateArn: "arn:aws:acm:{{AwsRegion}}:{{AwsAccountId}}:certificate/111-111-111-111"
```
Generates CloudFormation:
```
    "ApiGatewayDomainName": {
      "Type": "AWS::ApiGateway::DomainName",
      "Properties": {
        "CertificateArn": "arn:aws:acm:us-west-2:254924790709:certificate/111-111-111-111"
      }
    },
```
Looking at the DomainName support in humidifier shows an underscore after the DomainName.
https://github.com/jakejscott/Humidifier/blob/master/src/Humidifier/ApiGateway/DomainName.cs

When using `DomainName_` key in Deploy.yml, it generates the correct CloudFormation
```
        DomainName_: "{{EndpointDomainName}}"
```
