### ISSUE TITLE
Add support for collections of parameters

### ISSUE THREAD

**Issue by bjorg** [LambdaSharp/LambdaSharpTool#25]
```
  # This parameter is a collection of nested parameters. The names of the
  # sub-keys can be retrieved using `ReadAllKeys()` on `LambdaConfig`.
  # Parameters can be nested up to 15 levels deep. However, be aware that
  # app parameters a nested themselves three layer deep:
  # `{Deployment}/{AppName}/{GitSha}/`
  - Name: FileTypes
    Description: Sample collection of values
    Parameters:
      - Name: Item1
        Description: Description of Item1
        Value: first item in collection
      - Name: Item2
        Description: Description of Item2
        Value: second item in collection
```
