### ISSUE TITLE
Add default encryption key for deployment tier

### ISSUE THREAD

**Issue by bjorg** [LambdaSharp/LambdaSharpTool#29]
Consider adding a default secret key to bootstrap LambdaSharp deploy file.
```yaml
- Name: SecretsAlias
  Resource:
    Type: AWS::KMS::Alias
    Properties:
      AliasName: alias/LambdaSharpSecrets-{{Deployment}}
      TargetKeyId:
        Ref: LambdaSharpSecretsKey

- Name: SecretsKey
  Description: Manages secrets for LambdaSharp deployments
  Export: SecretsKey
  Resource:
    Type: AWS::KMS::Key
    Properties:
      Description: Manages secrets for LambdaSharp deployments
      Enabled: true
      EnableKeyRotation: true
      KeyPolicy:
        Version: "2012-10-17"
        Id: KeyPolicyForKMS
        Statement:
          - Sid: Enable IAM User Permissions
            Effect: Allow
            Principal:
              AWS: "arn:aws:iam::{{AwsAccountId}}:root"
            Action: "kms:*"
            Resource: "*"
```
