### ISSUE TITLE
Module: set permission for exported resources

### ISSUE THREAD

**Issue by bjorg** [LambdaSharp/LambdaSharpTool#37]
* allow specifying max permissions on exported resources
```yaml
- Export: MyDynamoTable
  Resource:
    Type: AWS::DynamoDB::Table
    Allow: ReadOnly
```
