### ISSUE TITLE
Module: Nested Modules

### ISSUE THREAD

**Issue by bjorg** [LambdaSharp/LambdaSharpTool#38]
Allow modules to instantiate other modules as part of its deployment.

Sample notation/food for thought:
```yaml
Variables:

    - Name: MyNestedModule
    Description: ...
    Module:
        # what about local vs. remote modules?
        ModuleName: MyModuleName
        Version: 1.0
        Properties:
        MyNestedProperty: !Ref Foo
        MyOtherNestedProperty: !Sub "!Import:${ModuleStackName}.SomeValueToImport"

    - Module: MyNestedModule
    Description: A local module definition
    Properties: # module deployment properties
        Name: Value

    - RemoteModule: MyNestedModule
    Version: 0.4 # requested version of module; recommended for non-local modules
    Source: https://example.com/MyRemoveModule-0.4.zip # source location for non-local module definitions
    Description: A remote module definition
    Properties: # module deployment properties
        Name: Value
```
