### ISSUE TITLE
Allow interactive prompts in deployment files

### ISSUE THREAD

**Issue by bjorg** [LambdaSharp/LambdaSharpTool#4]
# Use Case
For files that require specific configurations to be selected or API keys to be provided, it would be convenient if the the λ# tool had a facility to interactively prompt for these values.

Furthermore, these values could be stored in the parameter store so that they don't need to be entered again every time. The latter is convenient when base deployment files are updated and need to be re-run.

# Notation
Here's the proposed notation for variables to have values that are prompted.

## Plain Value
```yaml
Variables:
  MyVariable:
    Prompt: What value would you like to have?
```

## Encrypted Value
```yaml
Variables:
  MySecreteVariable:
    Prompt: What value would you like to have?
    Encrypt: NameOfEncryptionKey
```

 ## List of Possible Values
Can optionally also be encrypted.
```yaml
Variables:
  MyVariable:
    Prompt: What value would you like to have?
    Choices:
      - Text: First choice values
        Value: first
      - Text: Second choice values
        Value: second
```
