### ISSUE TITLE
Use macros to make DynamoDB resource creation simpler

### ISSUE THREAD

**Issue by bjorg** [LambdaSharp/LambdaSharpTool#51]
* ~~support auto-scaling~~ [pay-as-you-go support was added by AWS on 2018-11]
* use macro to make DynamoDB table definitions simpler
    ```yaml
    Parameters:
    - Name: MyDynamoDBTable
        Resource:
        Type: AWS::DynamoDB::Table
        Allow: Subscribe
        Properties: !$SimpleTable
            Keys:
            - MessageId S PRIMARY
            ReadCapacity: 1
            WriteCapacity: 1
    ```
