### ISSUE TITLE
Error when creating a resource with custom resource type

### ISSUE THREAD

**Issue by bjorg** [LambdaSharp/LambdaSharpTool#85]
When compiling this snippet, the custom resource type is incorrectly translated to `Custom::LexBot::Builder` instead of just `Custom::LexBotBuilder` 

```yaml
  - Var: CustomResourceLexBot
    Resource:
      Type: LexBot::Builder
```
